name: repack-llvm-manual

on:
  workflow_dispatch:
    inputs:
      version:
        description: "LLVM version (example: 21.1.8)"
        required: true
        default: 21.1.8
        type: string
      publish:
        description: "Publish GitHub release"
        required: true
        default: false
        type: boolean

jobs:
  repack:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - uses: bazelbuild/setup-bazelisk@6ecf4fd8b7d1f9721785f1dd656a689acf9add47

      - name: Repack
        run: tools/repack-llvm.sh "${{ inputs.version }}"

      - name: Upload workflow artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: llvm-project-${{ inputs.version }}.src.tar.zst
          path: |
            out/llvm-project-${{ inputs.version }}.src.tar.zst
            out/llvm-project-${{ inputs.version }}.src.tar.zst.sha256
          if-no-files-found: error

      - name: Attest release artifacts
        uses: actions/attest-build-provenance@43d14bc2b83dec42d39ecae14e916627a18bb661
        with:
          subject-path: |
            out/llvm-project-${{ inputs.version }}.src.tar.zst
            out/llvm-project-${{ inputs.version }}.src.tar.zst.sha256

  publish-release:
    if: ${{ inputs.publish }}
    needs: repack
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Download workflow artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: llvm-project-${{ inputs.version }}.src.tar.zst
          path: out

      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          tools/create-release.sh \
            "${{ inputs.version }}" \
            "out/llvm-project-${{ inputs.version }}.src.tar.zst" \
            "out/llvm-project-${{ inputs.version }}.src.tar.zst.sha256"
