name: reusable-repack

on:
  workflow_call:
    inputs:
      version:
        description: "LLVM version to repack"
        required: true
        type: string

jobs:
  repack:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      attestations: write
      artifact-metadata: write
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: bazelbuild/setup-bazelisk@6ecf4fd8b7d1f9721785f1dd656a689acf9add47 # v3

      - name: Repack
        run: tools/repack-llvm.sh "${{ inputs.version }}"

      - name: Upload workflow artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: llvm-project-${{ inputs.version }}.src.tar.zst
          path: |
            out/llvm-project-${{ inputs.version }}.src.tar.zst
            out/llvm-project-${{ inputs.version }}.src.tar.zst.sha256
          if-no-files-found: error

      - name: Attest release artifacts
        id: attest
        uses: actions/attest@281a49d4cbb0a72c9575a50d18f6deb515a11deb # v4
        with:
          subject-path: |
            out/llvm-project-${{ inputs.version }}.src.tar.zst
            out/llvm-project-${{ inputs.version }}.src.tar.zst.sha256

      - name: Normalize attestation bundle filename
        run: |
          mv \
            "${{ steps.attest.outputs.bundle-path }}" \
            "out/llvm-project-${{ inputs.version }}.src.tar.zst.attestation.jsonl"

      - name: Upload attestation bundle artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: llvm-project-${{ inputs.version }}.src.tar.zst.attestation
          path: out/llvm-project-${{ inputs.version }}.src.tar.zst.attestation.jsonl
          if-no-files-found: error
