name: reusable-repack

on:
  workflow_call:
    inputs:
      version:
        description: "LLVM version to repack"
        required: true
        type: string

jobs:
  repack:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: bazelbuild/setup-bazelisk@6ecf4fd8b7d1f9721785f1dd656a689acf9add47 # v3

      - name: Repack
        run: tools/repack-llvm.sh "${{ inputs.version }}"

      - name: Upload workflow artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: llvm-project-${{ inputs.version }}.src.tar.zst
          path: |
            out/llvm-project-${{ inputs.version }}.src.tar.zst
            out/llvm-project-${{ inputs.version }}.src.tar.zst.sha256
          if-no-files-found: error

      - name: Attest release artifacts
        uses: actions/attest-build-provenance@43d14bc2b83dec42d39ecae14e916627a18bb661 # v3
        with:
          subject-path: |
            out/llvm-project-${{ inputs.version }}.src.tar.zst
            out/llvm-project-${{ inputs.version }}.src.tar.zst.sha256
